name: Artemis Score Stats (PRs & Main Branch)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "Full build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
      with:
        submodules: true

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: Cache Distributions
      uses: actions/cache@v4
      with:
        path: ./dist
        key: cache-dist-${{github.run_id}}

    - name: Verify with Maven
      run: mvn -B clean verify

    - name: Build with Maven
      run: mvn -B clean package -DskipTests

    - name: Save Final JAR
      uses: actions/upload-artifact@v4
      with:
        name: "JAR File"
        path: "target/artemis-score-stats-complete.jar"
